# github.com/go-task/task

default:
  dir: rondymesquita.github.io
  cmds:
    - task: build

serve:
  dir: rondymesquita.github.io
  cmds:
    - hugo serve -D

build:
  dir: rondymesquita.github.io
  cmds:
    - hugo -b http://rondymesquita.github.io

serve-static:
  dir: rondymesquita.github.io
  cmds:
    - hugo -D -b http://localhost:1313
    - task: serve

configure:
  dir: rondymesquita.github.io/public
  cmds:
    - git remote add origin git@github.com:rondymesquita/rondymesquita.github.io.git

deploy:
  dir: rondymesquita.github.io/public
  cmds:
    - task: build
    - git add -A
    - git commit -m "$(date)"
    - git push origin master
    - echo "Access http://rondymesquita.github.io"
